# Site settings
title: Teresa Ontiveros personal website 
description: Teresa Ontiveros 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Teresa Ontiveros
user_description: An enthusiastic programmer ready to join a team!
user_title: Software Engineer
email: tontiveros@arcadia.edu
github_username:  https://github.com/tontiveros

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
